services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: invoice-agent-api
    ports:
      - "8008:8008"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    env_file:
      - .env
    networks:
      - invoice-network
    restart: always

  mongodb:
    image: mongo:latest
    container_name: invoice-agent-mongodb
    ports:
      - "27027:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    networks:
      - invoice-network
    restart: always

networks:
  invoice-network:
    driver: bridge

volumes:
  mongodb_data:
